---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt-get update
      - apt-get upgrade -y
      - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev
        libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - npm cache clean --force
      - npm install
  build:
    commands:
      - npm run test
  post_build:
    commands:
      - echo "Post build step"
